### ISSUE TITLE
Change hack IPv6 addr parser to the new function call on the ip-address module

### ISSUE THREAD

**Issue by diasdavid** [diasdavid/js-libp2p-swarm#4]
Did this ugly function - https://github.com/diasdavid/node-ipfs-swarm/blob/master/src/identify/index.js#L97-L111 - to get the correct representation of an IP addrs, due to the fact that Node.js represents every IPv4 addr in a IPv6, which would be ok, if we didn't have to cope with NAT hole punching.

But thanks to the core maintainer of `ip-address`, we can replace most of it, see: 
https://github.com/beaugunderson/ip-address/issues/24#issuecomment-123917584

**Comment by masylum** [comment]
https://github.com/diasdavid/js-libp2p-swarm/pull/17
