### ISSUE TITLE
`swarm.close()` should call `conn.end()` instead of `muxer.end()` on `muxedConns`

### ISSUE THREAD

**Issue by bgrieder** [diasdavid/js-libp2p-swarm#43]
https://github.com/diasdavid/js-libp2p-swarm/blob/master/src/index.js#L322

The line should read `this.muxedConns[key].conn.end()`

 - `end()` not a registered method of "muxers"
 - failure to close these connections hangs the `handling` peer on `close()`

**Comment by diasdavid** [comment]
.end() is a method available on the muxer object (see: https://github.com/indutny/spdy-transport/blob/master/test/both/transport/connection-test.js#L89) 

Can you make a test reproducing the error you are seeing?

**Comment by bgrieder** [comment]
So I guess you expect all "Muxers" to implement the same interface as that of spdy-transport ? 
Since the expected methods are not "shadowed" [there](https://github.com/diasdavid/js-libp2p-spdy/blob/master/src/index.js), it is hard to know.

What happens when this Muxer is registered is that, if I do not `end` the connection(s) on the peer that registers the handler, before calling swarm.close() on that peer, muxedConns are still opened and the peer hangs.
Same issue with the dialing peer.

Please note that I am not using the head versions of the packages but the released versions. This problem may not exist anymore, in which case, I would appreciate you releasing those packages.
Thanks.

**Comment by diasdavid** [comment]
I see. Note that it is up to the application developer to close the stream their app opens, calling .end() on the muxer (and same applies for the underlying socket) will only finish once all the multiplexed streams are closed.

Our accepted stream muxers must follow https://github.com/diasdavid/interface-stream-muxer, I'm aware that closing the muxer is not part of the spec, I need to update that. This means that libp2p-multiplex should offer the same API call to end the muxer.

**Comment by bgrieder** [comment]
OK. Fair enough; I still would prefer that closing `swarm.close()` just does that and does not hang whatever the state of the underlying connections bu I guess that is a matter of opinion. Closing

**Comment by diasdavid** [comment]
I don't see it as `opinion`, any transport like implementation (http, tcp, utp, etc) will only completely shutdown after all the sockets on top are closed too. Typically it offers also a .destroy method in case the developer is ok with blowing up all the transfers.
