### ISSUE TITLE
Hanging on `msI.handle` calling swarm.dial for the second time

### ISSUE THREAD

**Issue by nicola** [diasdavid/js-libp2p-swarm#55]
I am running this code over [https://github.com/nicola/js-gossip-cyclon](here)

When I run the last two tests ([here](https://github.com/nicola/js-gossip-cyclon/blob/master/test/cyclon.spec.js#L114-L131)) my code hangs at [index.js#L321](https://github.com/diasdavid/js-libp2p-swarm/blob/master/src/index.js#L321). In other words these last two tests call listen on a port, dial and disconnect, however the second time my code hangs.

After doing some console logging I realized it hangs exactly in this line: [index.js#L321](https://github.com/diasdavid/js-libp2p-swarm/blob/master/src/index.js#L321)

I haven't had enough time to dive deeper. Do you have any hint on what this might be?

**Comment by nicola** [comment]
I just updated to v0.12.10 and it works all fine!
It must have been a bug I run into 0.10!

**Comment by dignifiedquire** [comment]
js-ipfs is only being tested on Node 4, 5 and 6 so I strongly recommend upgrading to one of those.

**Comment by nicola** [comment]
When I said v0.12.10 I mean libp2p-swarm's version (not node!)

**Comment by dignifiedquire** [comment]
Ahh okay good :) You had me worried there for a moment
