### ISSUE TITLE
RFC - swarm revisit

### ISSUE THREAD

**Issue by diasdavid** [diasdavid/js-libp2p-swarm#8]
I'm in the middle of refactoring swarm to become more modular, enable more transports and offer a nice interface on how to `upgrade` connections.

We think of `upgrade` as a very important notion when we are talking about connections, we can see mechanisms like: stream multiplexing, congestion control, encrypted channels, multipath, simulcast, etc, as `upgrades` to a connection. A connection can be a simple and with no guarantees, drop a packet on the network with a destination thing, a transport in the other hand can be a connection and or a set of different streams that are mounted on top of each other, giving extra functionality to that connection and therefore `upgrading` it.

To avoid the confusion between connection, stream, transport, and other names that represent an abstraction of data flow between two points, we use terms as:

- stream - something that implements a Unix like type of stream, with mechanisms for back pressure
- ~~transport~~ connection - something that implements the transversal expectations of a stream between two peers, including the benefits of using a stream plus having a way to do half duplex, full duplex
- ~~connection~~ transport - something that as a dial/listen interface and return objs that implement a stream+~~transport~~connection interface

Types of upgrades to a ~~transport~~connection+stream:

- encrypted channel (with TLS for e.g)
- congestion flow (some transports don't have it by default)
- multipath (open several connections and abstract it as a single connection)
- simulcast (still really thinking this one through, it might be interesting to send a packet through different connections under some hard network circumstances)
- stream-muxer - this a special case, because once we upgrade a ~~transport~~connection+stream to a stream-muxer, we can open more streams (multiplex them) on a single stream, also enabling us to reuse the underlying dialed ~~connection~~transport

We also want to enable flexibility when it comes to upgrading a stream, for example, we might that all dialed transports pass through the encrypted channel upgrade, but not the congestion flow, specially when a transport might have already some underlying properties (UDP vs TCP vs WebRTC vs every other transport protocol)

This will all be included as API options for swarm :)

**Comment by diasdavid** [comment]
For more info : https://github.com/diasdavid/specs/blob/libp2p-spec/protocol/network/7-properties.md

**Comment by jbenet** [comment]
\<semantic-bikeshedding-that-is-not-unimportant>

- people (including us) refer to `UDP, DCCP, UTP, SCTP, UDT, CJDNS` as "transport protocols"  (it's the transport part of the network stack). which IMO includes the `connection` part above. (i might swap the "transport" and "connection" definitions above, in that "dial and listen return connections")
- it is fine to collectively refer to the whole thing (stream, connections, and transport) as a "transport protocol"
- on `upgrade`, i like the nomenclature and idea. i do want to make sure "upgrades" don't by definition imply "online" (i.e. like multistream, it can be one-directional, and even written out to a file).
- for the "underlying properties" cases, maybe we can describe things as "layering one transport over another", and even as having "polyfills", like in the web. (e.g. https://github.com/jbenet/random-ideas/issues/34)

**Comment by diasdavid** [comment]
> `<semantic-bikeshedding-that-is-not-unimportant>`

<3

> - people (including us) refer to `UDP, DCCP, UTP, SCTP, UDT, CJDNS` as "transport protocols"  (it's the transport part of the network stack). which IMO includes the `connection` part above. (i might swap the "transport" and "connection" definitions above, in that "[dial and listen return connections](http://golang.org/pkg/net/#DialTCP)")

I've been spinning my head around this trying to make it as clean as possible (lot of bikeshedding discussions with myself). It becomes very hard or even impossible to make a nomenclature that conforms with every expectation made by the current "transport protocols", to solve this, what I feel it is right, is to make sure that when we want to use the definitions above, we say 'in swarm context' or prefixed like 'swarm-connection, swarm-transport, swarm-stream', so that the communication is passed effectively.

That said, and after rereading your point several times, I now start to feel it would indeed make more sense to swap them as you proposed (initially it sounded weird for me to have a 'transport.dial', but now definitely makes more sense to have a 'connection.state' than a 'transport.state'. Thanks! :)

> - it is fine to collectively refer to the whole thing (stream, connections, and transport) as a "transport protocol"

Following the above, sets and mixes of  'swarm-stream + swarm-connection + swarm-transport' will indeed compose the protocols we know :) 

> - on `upgrade`, i like the nomenclature and idea. i do want to make sure "upgrades" don't by definition imply "online" (i.e. like multistream, it can be one-directional, and even written out to a file).

Since (now with nomenclature update), a transport.dial would return a impl of a abstract-connection interface, then that connection might be half duplex and when we call it to upgrade, the upgrade module will do its multistream thing to 'upgrade' that connection, meaning, that it will fulfil what you are looking for :)

**Comment by jbenet** [comment]
yeah all this sounds right to me. thanks

@diasdavid encourage you to write some Go with the `net` package. they did a pretty nice job with the abstractions.
